version: '3.1'

services:

  ghost:
    image: ghost:1-alpine
    restart: always
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: oosh0phe3xaep2AhZ8Xoo6th
      database__connection__database: ghost
    deploy:
      labels:
        - "traefik.docker.network = traefik-web"
        - "traefik.frontend.rule = Host:ghost.cinosure.com"
        - "traefik.port = 2368"
    volumes:
      - ghost:/var/lib/ghost/content

    networks:
      - traefik-web
      - ghost-net

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: oosh0phe3xaep2AhZ8Xoo6th
    networks:
      - ghost-net
    volumes:
      - db:/var/lib/mysql

networks:
  traefik-web:
    external: true
  ghost-net:
    driver: overlay
    external: false

volumes:
   ghost:
   db:
