version: "3.3"
services:
  traefik:
    image: traefik
    command:
      - "--web"
      - "--docker"
      - "--docker.swarmmode"
      - "--docker.domain=traefik"
      - "--docker.watch"
      - "--api"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--acme"
      - "--acme.storage=/certificates/acme.json"
      - "--acme.entryPoint=https"
      - "--acme.httpChallenge.entryPoint=http"
      - "--acme.onHostRule=true"
      - "--acme.onDemand=false"
      - "--acme.email=jon@whiteheat.org.uk"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-public-certificates:/certificates
    networks:
      - traefik-web
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    deploy:
      placement:
        constraints: [node.role==manager]
      replicas: 1
      labels:
        - "traefik.frontend.rule=Host:traefik.cinosure.com"
        - "traefik.enable=true"
        - "traefik.port=8080"

networks:
  traefik-web:
    external: true
volumes:
  traefik-public-certificates:
    external: true
