version: '3.6'

services:
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wordpress-net

    app:
      image: wordpress:latest
      depends_on:
        - db
      ports:
        - 8000:80
      restart: always
      environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: wordpress
      networks:
        - wordpress-net
      volumes:
        - app-data:/var/www/html
      deploy:
        labels:
          - "traefik.docker.network=traefik-web"
          - "traefik.frontend.rule=Host:wordpress.cinosure.com"
          - "traefik.port=80"

volumes:
  db-data:
  app-data:
networks:
  wordpress-net:
